# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "usbhid" "usb_storage" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fe0f794b-ab92-4e8f-b617-3053f29aaf1e";
      fsType = "ext4";
    };

  fileSystems."/mnt/share" =
    { device = "share";
      fsType = "9p";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F26-863F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6f8df633-7520-40a7-aef5-b53270a0fb60"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
